### PR TITLE
Add a reminder to ssh-add

### PR DESCRIPTION
**Pull request by dryewo**
I tripped on this multiple times, without adding the key to SSH Agent `ssh` just says "Permission denied (public key)".

This additional message would have helped.

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
Can you make it print the warning only if the SSH agent reports no installed keys? It should be easy to check with `ssh-add -l`.

**Comment by aermakov-zalando** [comment]
It might make sense to also print it as a warning.

**Comment by dryewo** [comment]
is it safe to assume that every computer has `ssh-add` installed?

**Comment by aermakov-zalando** [comment]
@dryewo you can just ignore it if it's not. but if it's installed and reports some keys, there's no point in printing the warning.

**Comment by aermakov-zalando** [comment]
👍

**Comment by dryewo** [comment]
:+1:

**Pull request merged**
