### PR TITLE
#29 Perform OAuth2 Implicit Grant Flow to get access token

### PR DESCRIPTION
**Pull request by vroldanbet**
- addresses issue #29
- updated to new stups-zign
- replaced get_named_token calls with get_token

### CODE REVIEW

**Comment by hjacobs** [comment]
We should also remove the command line options like username and password.

**Comment by vroldanbet** [comment]
@hjacobs done. It is still possible to pass a username as "myuser@host".

**Comment by hjacobs** [comment]
@vroldanbet you can update to https://github.com/zalando-stups/zign/releases/tag/1.1.26

**Comment by vroldanbet** [comment]
@hjacobs done

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
