### PR TITLE
Automatically run SSH command through --connect flag (#9)

### PR DESCRIPTION
**Pull request by outime**

### CODE REVIEW

**Comment by szuecs** [comment]
@outime Can you change the commit message to have the GH issue number included according to zappr?
Commit message has to have the Issue, according to https://zappr.readthedocs.io/en/latest/setup/#zappr-features-and-their-configuration-options last topic on the bottom of that page.
Thanks!

**Comment by outime** [comment]
@szuecs done!

**Comment by szuecs** [comment]
+1

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
